<?php

namespace Cms\Modules\Admin\Tests;

use Cms\Modules\Admin\AdminServiceProvider;
use Cms\Modules\Core\Tests\CoreTestCase;

abstract class AdminTestCase extends CoreTestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app): array
    {
        return [
            AdminServiceProvider::class,
        ];
    }

    protected function getEnvironmentSetUp($app)
    {
        // perform environment setup
    }
}

